#port
server:
  port: 8081

#kafka
kafka:
  subscribed-topic:
    name: transaction-request
  topic-to-publish:
    name: transaction-response

#mongodb
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.oksp7.mongodb.net/bootcamp_customer?retryWrites=true&w=majority
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transaction-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
#base-api:
#  base-url: http://localhost:8000

#eureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

#circuitBraker
resilience4j:
  circuitbreaker:
    instances:
      customerTypeInfoService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        timeoutDuration: 2s
      productInfoService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        timeoutDuration: 2s
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

